### ISSUE TITLE
Receptacles should not be part of the monocle window cycle

### ISSUE THREAD

**Issue by ortango** [diogox/bspm#10]
this would be consistent with current bspwm monocle behavior (they are not focusable, so you cannot switch to them normally with `node -f`).

**Comment by diogox** [comment]
Good catch! This latest commit should fix it according to my testing.

Can you test on your end and close the ticket if it works as expected? Thanks!

**Comment by diogox** [comment]
Pushed `v0.0.7` for your convenience, btw :smile:

**Comment by ortango** [comment]
just gave it a whirl. all is good over here, including the issue linked with force quitting and receptacles.
