### ISSUE TITLE
Force-quitting nodes does not get handled by monocle mode

### ISSUE THREAD

**Issue by diogox** [diogox/bspm#9]
It seems that force quitting nodes (through something like `xkill`) will not handle it as a node_removal, leaving the screen empty, instead of showing the node beneath.

This might require non-bspwm features to solve, since bspwm solves this issue by not solving it. It just shows all nodes all the time, meaning that when the node gets force-quitted, the other nodes are already below.

If this can't be solved, or can't be solved easily, as I suspect, it's also an option to leave it like it is. As you simply have to toggle off and on to return to a functioning state.

**Comment by ortango** [comment]
what version of `xkill` are you using? i can not reproduce this.

bspwm _should_ catch destroy_notify events and print the node_remove report in most cases. one case it doesn't is `bspc node -k`. in that case bspwm catches the event but the window is already gone and locate node fails (so the report isn't printed).

using `killw` from wmutils also uses xcb_kill_client, but bspwm does get the event in time. difference being that `node -k` runs remove_node immediately (before unmap or destroy notifies, leading to the locate node failure).

**Comment by diogox** [comment]
You're right, I was using `bspc node -k`.

When I created the issue I didn't think there would be a difference, so I just wrote `xkill`, instead of checking :smile: 

I guess this doesn't really need solving then, since I can just suggest alternatives like `xdotool getwindowfocus windowkill` and `xkill -id $(xprop -root _NET_ACTIVE_WINDOW | cut -d\# -f2)` in the `README`.

It's not pretty. But it'll do for now, I think.

In the future I can look into implementing something like `bspm monocle --kill-focused-node`. Or make `bspm` override bspc's `bspc node -k` somehow to one of the commands above. Though the former is something I'd like to avoid, and the latter a bit too intrusive for my taste.

**Comment by ortango** [comment]
>I guess this doesn't really need solving then

yea

>In the future I can look into implementing something like bspm monocle --kill-focused-node

i think this shouldn't be necessary. it really seems like a bspwm bug. bspwm will also use xcb_kill_client on clients who don't support WM_DELETE_WINDOW. like with `killw` a node_remove event is printed. i am not sure why `remove_node()` is being run when it is for `node -k` but it doesn't seem like there is a reason for it (since everything seems to work fine in those cases).

i will file an issue with bspwm about this unless you want to.

**Comment by diogox** [comment]
Go ahead, I appreciate it. You can clearly explain it better than I can. 😄

**Comment by ortango** [comment]
some other notes on this issue:

* you can use something like `bspc node pointed -c` on a keybind as a native `xkill`-like replacement
* the `remove_node()` in `kill_node()` is required for destroying receptacles (but the code is from before they were introduced).
* similar to this issue, placing a node on a receptacle that is in a bspm monocled desktop causes bspm to miss the tracking of the destroyed receptacle. this might be addressed with a fix for #10 though.

**Comment by diogox** [comment]
* I highly prefer that command to the ones I added to the `README`. I'll change it to just have that command. But first, could you tell me if there's a difference between using `pointed` and `focused` there? i think `focused` makes more sense, but I'm not 100% sure what `pointed` does (although, by the name, I guess it selects the node under the pointer). Oh, and also, it you're sure that kills and unresponsive node. I couldn't think of a way to easily test that.
* Well, I guess we'll just have to live with advising against using `bspc node -k` for now.
* I've just pushed a change to fix issue #10. Could you install `v0.0.7` and tell me if this is still an issue? I don't have a workflow with receptacles, so I can't easily test it rn.

Once again, thanks for your help on this :)

**Comment by ortango** [comment]
>Oh, and also, it you're sure that kills and unresponsive node.

no, you're right, it will not do that. it will always attempt to close cleanly if the window supported it.

another alternative is `xdo kill`. just mentioning it because xdo is another baskerville program. more people will have xdotool or xkill installed though.

>but I'm not 100% sure what pointed does (although, by the name, I guess it selects the node under the pointer).

yea, using pointed just seemed closer to the xdotool or xkill style selection.

>Could you install v0.0.7 and tell me if this is still an issue? 

seems 100% fixed here

**Comment by diogox** [comment]
Great, thanks for testing it for me :smile: 

I'll go ahead and add `xdo kill` as a suggestion to the `README`, and close this issue for now.

**Comment by ortango** [comment]
just a note, bspwm has fixed the issue -   baskerville/bspwm@6fadfdb6087b4b9127e0b4f392535ff27f5079b5. `node -k` should now fire off a node_remove event.

although it's not in a stable release yet

**Comment by diogox** [comment]
Thanks for letting me know! I'll keep an eye out for when it reaches stable so I can update the `README` :smile:
